# 1

Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [20]:
#pip install numpy
import numpy as np

In [21]:
array=np.array([1,2.0,3.6,4.8,5,6,7,3.8,9.3,10],dtype="int")
array

array([ 1,  2,  3,  4,  5,  6,  7,  3,  9, 10])

In [24]:
np.shape(array)

(10,)

In [23]:
print(array.size)

10


In [29]:
array.ndim

1

# 2
İki ve üç boyutlu arrayler oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [36]:
array2=np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
array2
array3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])


array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [37]:
print(array2.ndim)
print(array3.ndim)

2
3


In [41]:
array3.size

12

In [40]:
array2.size

12

In [42]:
np.shape(array2)

(2, 6)

In [43]:
np.shape(array3)

(2, 2, 3)

In [44]:
array2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [46]:
array2[:1]

array([[1, 2, 3, 4, 5, 6]])

In [47]:
array2[1:]

array([[ 7,  8,  9, 10, 11, 12]])

In [48]:
array3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [49]:
array3[0,1:,1]

array([5])

In [52]:
array3[0,1,1]

5

In [53]:
array3[1,0,2]

9

In [54]:
array2[0,4]

5

# 3

Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturalım. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [83]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [84]:
arr2=np.array([[0,2,4,6,8],[1,3,5,7,9]])
arr2

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [85]:
arr3=np.array([[[1,3,5,7],[2,4,6,8]],[[9,7,5,0],[3,4,5,1]]])
arr3

array([[[1, 3, 5, 7],
        [2, 4, 6, 8]],

       [[9, 7, 5, 0],
        [3, 4, 5, 1]]])

In [86]:
arr1[4]

5

In [87]:
arr2[0,4]

8

In [88]:
arr3[1,0:,:2]

array([[9, 7],
       [3, 4]])

In [89]:
arr3[1,1:,:2]

array([[3, 4]])

In [90]:
arr2[1,:3]

array([1, 3, 5])

# 4

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [60]:
x=np.zeros((2,5),dtype="int")
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [61]:
y=np.ones((2,5),dtype="int")
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [62]:
np.concatenate([x,y])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
np.concatenate([x,y],axis=1)

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])