# Pandas

Pandas kütüphanesi veriyi analiz etmek için kullanılır. Veri bilimi projelerinde,veri okuma, veri ön işleme gibi adımlarda kullanılır.
Pandasta en çok kullanılan veri yapılar Series ve DataFrame yapılarıdır.

**Seriler**

Seriler bir tablodaki sütunlar gibidir. Bir boyutlu arraylerdir.

In [6]:
#pip install pandas

In [9]:
import pandas as pd

In [10]:
seri = pd.Series([12,47,34,66,50])
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [11]:
type(seri)

pandas.core.series.Series

In [12]:
#index bilgisi verir
seri.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
#serideki eleman sayısını verir
seri.size

5

In [14]:
#boyut bilgisi verir
seri.ndim

1

In [15]:
#değerlere array formunda  erişmek istersek values methodunu kullanabiliriz
seri.values

array([12, 47, 34, 66, 50], dtype=int64)

In [16]:
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [17]:
#fonksiyonun içine girilen değer kadar veriyi gösterir
seri.head(3)

0    12
1    47
2    34
dtype: int64

In [18]:
seri.tail(3)

2    34
3    66
4    50
dtype: int64

In [19]:
#serilerde de indexing ve slicing işlemlerini yapabiliyoruz
seri[0]

12

In [20]:
seri[2]

34

In [21]:
seri[3]

66

In [22]:
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [23]:
seri[0:2]

0    12
1    47
dtype: int64

In [24]:
seri[1:4]

1    47
2    34
3    66
dtype: int64

In [25]:
#indexleri değiştirebilir,isimlendirme yapabiliriz
seri2 = pd.Series([15,45,63,85,41],index=[1,8,5,3,6])
seri2

1    15
8    45
5    63
3    85
6    41
dtype: int64

In [26]:
seri2[1]

15

In [27]:
seri2[5]

63

In [28]:
seri3 = pd.Series([15,45,63,85,41],index=["a","b","c","d","e"])
seri3

a    15
b    45
c    63
d    85
e    41
dtype: int64

In [29]:
seri3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [30]:
seri3["b"]

45

In [31]:
seri3["d"]

85

In [32]:
seri3["a":"d"]

a    15
b    45
c    63
d    85
dtype: int64

In [33]:
#sözlük üzerinden seri oluşturalım
sozluk = {"Ayşe":42,
          "Elif":27,
          "Fatma":36}
sozluk

{'Ayşe': 42, 'Elif': 27, 'Fatma': 36}

In [34]:
yeni_sozluk = pd.Series(sozluk)
yeni_sozluk

Ayşe     42
Elif     27
Fatma    36
dtype: int64

In [35]:
yeni_sozluk["Ayşe"]

42

In [36]:
#######################
import numpy as np
dizi = np.random.randint(50,size=6)
dizi

array([29, 15, 41, 36, 25, 19])

In [37]:
seri2 = pd.Series(dizi)
seri2

0    29
1    15
2    41
3    36
4    25
5    19
dtype: int32

In [38]:
seri2.index

RangeIndex(start=0, stop=6, step=1)

In [39]:
seri2.index = ["a","b","c","d","e","f"]

In [40]:
seri2

a    29
b    15
c    41
d    36
e    25
f    19
dtype: int32

In [41]:
seri2["b"]

15

In [42]:
seri2[["b","d"]]

b    15
d    36
dtype: int32

In [43]:
seri2[["a","c","f"]]

a    29
c    41
f    19
dtype: int32

In [44]:
seri2[["b","d"]] = 55
seri2

a    29
b    55
c    41
d    55
e    25
f    19
dtype: int32

**DataFrame**

In [45]:
pd.DataFrame(seri2)

0
a  29
b  55
c  41
d  55
e  25
f  19

In [46]:
pd.DataFrame(seri2,columns=["Sayılar"])

Sayılar
a       29
b       55
c       41
d       55
e       25
f       19

In [49]:
yeni_dizi=np.random.randint(25,size=12).reshape(4,3)
yeni_dizi

array([[19, 11,  2],
       [22,  5,  0],
       [ 9,  2,  2],
       [ 1, 20, 15]])

In [50]:
df = pd.DataFrame(yeni_dizi,columns=["col1","col2","col3"])
df

col1  col2  col3
0    19    11     2
1    22     5     0
2     9     2     2
3     1    20    15

In [51]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [52]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [53]:
df.columns=["1.Sütun","2.Sütun","3.Sütun"]
df

1.Sütun  2.Sütun  3.Sütun
0       19       11        2
1       22        5        0
2        9        2        2
3        1       20       15

In [54]:
#satır ve sütun bilgisi verir
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['1.Sütun', '2.Sütun', '3.Sütun'], dtype='object')]

In [55]:
df.ndim

2

In [56]:
df.shape

(4, 3)

In [57]:
df.values

array([[19, 11,  2],
       [22,  5,  0],
       [ 9,  2,  2],
       [ 1, 20, 15]])

In [58]:
#Bir sözlükten DataFrame oluşturalım
a = np.random.randint(10,size=5)
b = np.random.randint(10,size=5)
c = np.random.randint(10,size=5)
print(a)
print(b)
print(c)

[8 7 9 4 8]
[9 4 5 5 0]
[3 2 4 3 9]


In [59]:
sozluk2 = {"Col1":a,"Col2":b,"Col3":c}
sozluk2

{'Col1': array([8, 7, 9, 4, 8]),
 'Col2': array([9, 4, 5, 5, 0]),
 'Col3': array([3, 2, 4, 3, 9])}

In [60]:
data = pd.DataFrame(sozluk2)
data

Col1  Col2  Col3
0     8     9     3
1     7     4     2
2     9     5     4
3     4     5     3
4     8     0     9

In [61]:
data[0:3]

Col1  Col2  Col3
0     8     9     3
1     7     4     2
2     9     5     4

In [62]:
data[1:-1]

Col1  Col2  Col3
1     7     4     2
2     9     5     4
3     4     5     3

In [63]:
data[::2]

Col1  Col2  Col3
0     8     9     3
2     9     5     4
4     8     0     9

In [64]:
data[1:4][["Col1","Col3"]]

Col1  Col3
1     7     2
2     9     4
3     4     3

In [65]:
data[0:3]["Col2"]

0    9
1    4
2    5
Name: Col2, dtype: int32

In [66]:
data[0:3][["Col2"]]

Col2
0     9
1     4
2     5

In [67]:
data[["Col1","Col3"]]

Col1  Col3
0     8     3
1     7     2
2     9     4
3     4     3
4     8     9

In [68]:
data[["Col2"]]

Col2
0     9
1     4
2     5
3     5
4     0

In [69]:
#Silme işlemi için drop kullanılır.
data

Col1  Col2  Col3
0     8     9     3
1     7     4     2
2     9     5     4
3     4     5     3
4     8     0     9

In [70]:
data.drop(1,axis=0)

Col1  Col2  Col3
0     8     9     3
2     9     5     4
3     4     5     3
4     8     0     9

In [71]:
data

Col1  Col2  Col3
0     8     9     3
1     7     4     2
2     9     5     4
3     4     5     3
4     8     0     9

In [72]:
#İşlemin kalıcı olması için inplace True yapılmalı
data.drop(1,axis=0,inplace=True)

In [73]:
data

Col1  Col2  Col3
0     8     9     3
2     9     5     4
3     4     5     3
4     8     0     9

In [74]:
new_data = data.drop("Col2",axis=1)
new_data

Col1  Col3
0     8     3
2     9     4
3     4     3
4     8     9

In [75]:
data

Col1  Col2  Col3
0     8     9     3
2     9     5     4
3     4     5     3
4     8     0     9

In [76]:
#Yeni bir sütun eklemek
data["Col4"] = data["Col1"]/data["Col2"]
data

Col1  Col2  Col3      Col4
0     8     9     3  0.888889
2     9     5     4  1.800000
3     4     5     3  0.800000
4     8     0     9       inf

In [77]:
seri2

a    29
b    55
c    41
d    55
e    25
f    19
dtype: int32

In [78]:
data2=pd.DataFrame(seri2)
data2

0
a  29
b  55
c  41
d  55
e  25
f  19

**Değişken Seçimi: loc & iloc**

**loc:** Etikete dayalı seçme işlemi gerçekleştirir. Seçmek istediğimiz satır ve sütunun adını belirtmek gerekir. Seçimlerde verilen aralığın son elemanını içerir.

[satır_adı,sütun_adı]

**iloc:** İndexe dayalı seçme işlemidir. Seçmek istenilen satır ve sütunun indexi belirtilir. Indexe dayalı bir yöntem olduğundan belirtilen aralığın son öğesini içermez.

[satır_indexi,sütun_indexi]

In [79]:
numbers = np.random.randint(40,size=(10,3))
numbers

array([[32, 27,  2],
       [17, 27, 17],
       [11, 14, 17],
       [ 0, 35, 33],
       [ 5, 25, 11],
       [12,  5, 37],
       [11, 27,  9],
       [18, 29,  0],
       [17,  1,  7],
       [25,  9, 11]])

In [80]:
df = pd.DataFrame(numbers,columns=["Col1","Col2","Col3"])
df

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [81]:
df.loc[0,"Col3"]

2

In [82]:
df.iloc[0,2]

2

In [83]:
df.loc[6,"Col2"]

27

In [84]:
df.iloc[6,1]

27

In [85]:
df

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [86]:
df.loc[2:8,"Col2":"Col3"]

Col2  Col3
2    14    17
3    35    33
4    25    11
5     5    37
6    27     9
7    29     0
8     1     7

In [87]:
df.iloc[2:9,1:3]

Col2  Col3
2    14    17
3    35    33
4    25    11
5     5    37
6    27     9
7    29     0
8     1     7

In [88]:
df.loc[0:5]

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37

In [89]:
df.loc[2:7]

Col1  Col2  Col3
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0

In [90]:
df.loc[2:7,"Col2"]

2    14
3    35
4    25
5     5
6    27
7    29
Name: Col2, dtype: int32

In [ ]:
#########

In [91]:
df

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [92]:
df["Col1"]

0    32
1    17
2    11
3     0
4     5
5    12
6    11
7    18
8    17
9    25
Name: Col1, dtype: int32

In [93]:
df["Col1"]>20

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: Col1, dtype: bool

In [94]:
df[df["Col1"]>20]

Col1  Col2  Col3
0    32    27     2
9    25     9    11

In [95]:
df[df["Col1"]>20][["Col1"]]

Col1
0    32
9    25

In [96]:
df

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [97]:
df[df["Col3"]<30]

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
4     5    25    11
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [98]:
df[df["Col3"]<30][["Col3"]]

Col3
0     2
1    17
2    17
4    11
6     9
7     0
8     7
9    11

In [99]:
df[df["Col3"]<30][["Col2","Col3"]]

Col2  Col3
0    27     2
1    27    17
2    14    17
4    25    11
6    27     9
7    29     0
8     1     7
9     9    11

In [100]:
df

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [101]:
df[(df["Col2"]>20) & (df["Col3"]<30)]

Col1  Col2  Col3
0    32    27     2
1    17    27    17
4     5    25    11
6    11    27     9
7    18    29     0

In [102]:
df.Col1

0    32
1    17
2    11
3     0
4     5
5    12
6    11
7    18
8    17
9    25
Name: Col1, dtype: int32

In [103]:
df["Col1"]

0    32
1    17
2    11
3     0
4     5
5    12
6    11
7    18
8    17
9    25
Name: Col1, dtype: int32

In [104]:
df[df.Col1 > 15]

Col1  Col2  Col3
0    32    27     2
1    17    27    17
7    18    29     0
8    17     1     7
9    25     9    11

In [105]:
#join ile birleştirme işlemi yapılır
df

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [106]:
df2 = df+50
df2

Col1  Col2  Col3
0    82    77    52
1    67    77    67
2    61    64    67
3    50    85    83
4    55    75    61
5    62    55    87
6    61    77    59
7    68    79    50
8    67    51    57
9    75    59    61

In [107]:
pd.concat([df,df2])

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11
0    82    77    52
1    67    77    67
2    61    64    67
3    50    85    83
4    55    75    61
5    62    55    87
6    61    77    59
7    68    79    50
8    67    51    57
9    75    59    61

In [108]:
pd.concat([df,df2],ignore_index=True)

Col1  Col2  Col3
0     32    27     2
1     17    27    17
2     11    14    17
3      0    35    33
4      5    25    11
5     12     5    37
6     11    27     9
7     18    29     0
8     17     1     7
9     25     9    11
10    82    77    52
11    67    77    67
12    61    64    67
13    50    85    83
14    55    75    61
15    62    55    87
16    61    77    59
17    68    79    50
18    67    51    57
19    75    59    61

In [109]:
df

Col1  Col2  Col3
0    32    27     2
1    17    27    17
2    11    14    17
3     0    35    33
4     5    25    11
5    12     5    37
6    11    27     9
7    18    29     0
8    17     1     7
9    25     9    11

In [110]:
df2.columns=["Col1","Col2","Col4"]
df2

Col1  Col2  Col4
0    82    77    52
1    67    77    67
2    61    64    67
3    50    85    83
4    55    75    61
5    62    55    87
6    61    77    59
7    68    79    50
8    67    51    57
9    75    59    61

In [111]:
pd.concat([df,df2])

Col1  Col2  Col3  Col4
0    32    27   2.0   NaN
1    17    27  17.0   NaN
2    11    14  17.0   NaN
3     0    35  33.0   NaN
4     5    25  11.0   NaN
5    12     5  37.0   NaN
6    11    27   9.0   NaN
7    18    29   0.0   NaN
8    17     1   7.0   NaN
9    25     9  11.0   NaN
0    82    77   NaN  52.0
1    67    77   NaN  67.0
2    61    64   NaN  67.0
3    50    85   NaN  83.0
4    55    75   NaN  61.0
5    62    55   NaN  87.0
6    61    77   NaN  59.0
7    68    79   NaN  50.0
8    67    51   NaN  57.0
9    75    59   NaN  61.0

In [112]:
#ikisinde de ortak olan sütunları birleştirir
pd.concat([df,df2],join="inner")

Col1  Col2
0    32    27
1    17    27
2    11    14
3     0    35
4     5    25
5    12     5
6    11    27
7    18    29
8    17     1
9    25     9
0    82    77
1    67    77
2    61    64
3    50    85
4    55    75
5    62    55
6    61    77
7    68    79
8    67    51
9    75    59

In [113]:
pd.concat([df,df2],axis=1)

Col1  Col2  Col3  Col1  Col2  Col4
0    32    27     2    82    77    52
1    17    27    17    67    77    67
2    11    14    17    61    64    67
3     0    35    33    50    85    83
4     5    25    11    55    75    61
5    12     5    37    62    55    87
6    11    27     9    61    77    59
7    18    29     0    68    79    50
8    17     1     7    67    51    57
9    25     9    11    75    59    61

In [ ]:
####################

In [114]:
data = pd.DataFrame({"Öğrenciler":["Ayşe","Mehmet","Fatma","Fatma","Mehmet","Ayşe","Ayşe","Fatma","Mehmet"],
                   "Dersler":["Matematik","Türkçe","Türkçe","Fen Bilgisi","Matematik","Fen Bilgisi","Türkçe","Matematik","Fen Bilgisi"],
                    "Puan":[80,75,92,78,64,84,73,94,90]})

data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [115]:
data2 = pd.DataFrame({"Öğretmenler":["Selin","Furkan","Emine"],
                   "Dersler":["Matematik","Türkçe","Fen Bilgisi"]})
data2

Öğretmenler      Dersler
0       Selin    Matematik
1      Furkan       Türkçe
2       Emine  Fen Bilgisi

In [116]:
pd.merge(data,data2)

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [117]:
new_data = pd.merge(data,data2,on="Dersler")
new_data

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [118]:
data["Öğrenciler"]

0      Ayşe
1    Mehmet
2     Fatma
3     Fatma
4    Mehmet
5      Ayşe
6      Ayşe
7     Fatma
8    Mehmet
Name: Öğrenciler, dtype: object

In [119]:
data[["Öğrenciler"]]

Öğrenciler
0       Ayşe
1     Mehmet
2      Fatma
3      Fatma
4     Mehmet
5       Ayşe
6       Ayşe
7      Fatma
8     Mehmet

In [120]:
data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [121]:
#Ayşenin ders ve puanına bakalım
data[data["Öğrenciler"]=="Ayşe"]

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73

In [122]:
data[data["Öğrenciler"]=="Mehmet"]

Öğrenciler      Dersler  Puan
1     Mehmet       Türkçe    75
4     Mehmet    Matematik    64
8     Mehmet  Fen Bilgisi    90

In [123]:
data[data["Öğrenciler"]=="Fatma"]

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
7      Fatma    Matematik    94

In [124]:
data[data["Öğrenciler"]=="Mehmet"][["Dersler","Puan"]]

Dersler  Puan
1       Türkçe    75
4    Matematik    64
8  Fen Bilgisi    90

In [125]:
data[data["Dersler"]=="Matematik"]

Öğrenciler    Dersler  Puan
0       Ayşe  Matematik    80
4     Mehmet  Matematik    64
7      Fatma  Matematik    94

In [126]:
data[data["Dersler"]=="Fen Bilgisi"]

Öğrenciler      Dersler  Puan
3      Fatma  Fen Bilgisi    78
5       Ayşe  Fen Bilgisi    84
8     Mehmet  Fen Bilgisi    90

In [127]:
data[data["Dersler"]=="Fen Bilgisi"][["Öğrenciler","Puan"]]

Öğrenciler  Puan
3      Fatma    78
5       Ayşe    84
8     Mehmet    90

In [128]:
data[data["Puan"]>80]

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
5       Ayşe  Fen Bilgisi    84
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [129]:
data[(data["Dersler"] =="Matematik") & (data["Puan"]>80)]

Öğrenciler    Dersler  Puan
7      Fatma  Matematik    94

In [130]:
data[(data["Dersler"] =="Türkçe") & (data["Puan"]<85)]

Öğrenciler Dersler  Puan
1     Mehmet  Türkçe    75
6       Ayşe  Türkçe    73

In [131]:
data.columns

Index(['Öğrenciler', 'Dersler', 'Puan'], dtype='object')

In [132]:
data_sıralama = data[data["Puan"]>80]
data_sıralama

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
5       Ayşe  Fen Bilgisi    84
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [133]:
data_sıralama.sort_values(by="Puan",ascending=True)

Öğrenciler      Dersler  Puan
5       Ayşe  Fen Bilgisi    84
8     Mehmet  Fen Bilgisi    90
2      Fatma       Türkçe    92
7      Fatma    Matematik    94

In [135]:
data_sıralama.sort_values(by="Puan",ascending=False)

Öğrenciler      Dersler  Puan
7      Fatma    Matematik    94
2      Fatma       Türkçe    92
8     Mehmet  Fen Bilgisi    90
5       Ayşe  Fen Bilgisi    84